### PR TITLE
Add `cargo-audit` and some minor improvements to the dev environment

### PR DESCRIPTION
**Pull request by Ma27**

### CODE REVIEW

**Comment by TrueDoctor** [comment]
We should rebuild the docker container once it is merged into master to pre-cache cargo audit

**Comment by Ma27** [comment]
> We should rebuild the docker container once it is merged into master to pre-cache cargo audit

That's IMHO not really necessary unless we need cargo-audit in our CI pipeline.

(We may want to refactor `shell.nix` to differentiate between CI-deps and "devtools" if we have more of that optional `buildInputs` in the future btw)

**Comment by TrueDoctor** [comment]
That would be great, because now the ci downloads cargo-audit on every build which slows down the ci process

**Comment by Ma27** [comment]
> That would be great, because now the ci downloads cargo-audit on every build which slows down the ci process

Can't we cache e.g. `/nix/store` and `~/.rustup` to reduce at least IO during a build?

The refactoring for the nix-shell expression is IMHO rather simple, will file a patch here tomorrow :)

**Comment by TrueDoctor** [comment]
We currently cache pretty much everything, but the cache depends on that shell.nix file: https://github.com/squirrel-labs/docker-rust-wasm/blob/master/Dockerfile
not an idele solution, but it works quite well

**Pull request merged**
